{ mkDerivation, base, bytestring, containers, glib, stdenv, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.23.0";
  sha256 = "c07ebe7dea2a3c2b0a980f7b958529920caeaf5966280c1317c5fbba2f6942b8";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi-base";
  description = "Foundation for libraries generated by haskell-gi";
  license = stdenv.lib.licenses.lgpl21;
}
