{ mkDerivation, base, bytestring, containers, glib, stdenv, text }:
mkDerivation {
  pname = "haskell-gi-base";
  version = "0.24.4";
  sha256 = "afd5ff5eeb9a49dff934b6bbdbfd90b125fc8cae006e958821108c79dd15b4f5";
  libraryHaskellDepends = [ base bytestring containers text ];
  libraryPkgconfigDepends = [ glib ];
  homepage = "https://github.com/haskell-gi/haskell-gi";
  description = "Foundation for libraries generated by haskell-gi";
  license = stdenv.lib.licenses.lgpl21;
}
